name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Get 01.m3u8
      run: |
        touch ./01.m3u8
        sudo cat >./01.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=jp0xRMIosSw)
        EOL
    - name: Get 02.m3u8
      run: |
        touch ./02.m3u8
        sudo cat >./02.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/c/yoyotvebc/live)
        EOL
    - name: Get 03.m3u8
      run: |
        touch ./03.m3u8
        sudo cat >./03.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=UyyXhyYrC3g)
        EOL
    - name: Get 04.m3u8
      run: |
        touch ./04.m3u8
        sudo cat >./04.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=gEUUu_asZrY)
        EOL
    - name: Get 05.m3u8
      run: |
        touch ./05.m3u8
        sudo cat >./05.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=75FIn7nO-EY)
        EOL
    - name: Get 06.m3u8
      run: |
        touch ./06.m3u8
        sudo cat >./06.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=zKfOUCq3rW8)
        EOL
    - name: Get 07.m3u8
      run: |
        touch ./07.m3u8
        sudo cat >./07.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=cPaTcemo47c)
        EOL
    - name: Get 08.m3u8
      run: |
        touch ./08.m3u8
        sudo cat >./08.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=CHDb5D0DCkw)
        EOL
    - name: Get 09.m3u8
      run: |
        touch ./09.m3u8
        sudo cat >./09.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=I1TUDXaEnbE)
        EOL
    - name: Get 10.m3u8
      run: |
        touch ./10.m3u8
        sudo cat >./10.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=756000
        $(youtube-dl -g https://www.youtube.com/watch?v=tMs4xVO_OAw)
        EOL
    - name: Get 11.m3u8
      run: |
        touch ./11.m3u8
        sudo cat >./11.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=wldWQnyVwpk)
        EOL
    - name: Get 12.m3u8
      run: |
        touch ./12.m3u8
        sudo cat >./12.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=lOnIaaIKdQM)
        EOL
    - name: Get 13.m3u8
      run: |
        touch ./13.m3u8
        sudo cat >./13.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=qX1W7lZQp5A)
        EOL
    - name: Get 14.m3u8
      run: |
        touch ./14.m3u8
        sudo cat >./14.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=i7GVhM60Hi4)
        EOL
    - name: Get 15.m3u8
      run: |
        touch ./15.m3u8
        sudo cat >./15.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=Lde1rqHuUpM)
        EOL
    - name: Get 16.m3u8
      run: |
        touch ./16.m3u8
        sudo cat >./16.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=4EwvSc9L_YU)
        EOL
    - name: Get 17.m3u8
      run: |
        touch ./17.m3u8
        sudo cat >./17.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=VCRlFfDAJvw)
        EOL
    - name: Get 18.m3u8
      run: |
        touch ./18.m3u8
        sudo cat >./18.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=Gv0f-iOviWQ)
        EOL
    - name: Get 19.m3u8
      run: |
        touch ./19.m3u8
        sudo cat >./19.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=pPUbVzTN7Mg)
        EOL
    - name: Get 20.m3u8
      run: |
        touch ./20.m3u8
        sudo cat >./20.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=W0bO0hBpmoM)
        EOL
    - name: Get 21.m3u8
      run: |
        touch ./21.m3u8
        sudo cat >./21.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=fkgDWd38jqQ)
        EOL
    - name: Get 22.m3u8
      run: |
        touch ./22.m3u8
        sudo cat >./22.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=jTS3A4D4x6Q)
        EOL
    - name: Get 23.m3u8
      run: |
        touch ./23.m3u8
        sudo cat >./23.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=ABn_ccXn_jc)
        EOL
    - name: Get 24.m3u8
      run: |
        touch ./24.m3u8
        sudo cat >./24.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=lu_BJKxqGnk)
        EOL
    - name: Get 25.m3u8
      run: |
        touch ./25.m3u8
        sudo cat >./25.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
    - name: Get 26.m3u8
      run: |
        touch ./26.m3u8
        sudo cat >./26.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=yguQ1SzPM5U)
        EOL
    - name: Get 27.m3u8
      run: |
        touch ./27.m3u8
        sudo cat >./27.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=5n0y6b0Q25o)
        EOL
    - name: Get 28.m3u8
      run: |
        touch ./28.m3u8
        sudo cat >./28.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=FoBfXvlOR6I)
        EOL
    - name: Get 29.m3u8
      run: |
        touch ./29.m3u8
        sudo cat >./29.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=CKjSm5ZeehE)
        EOL
    - name: Get 30.m3u8
      run: |
        touch ./30.m3u8
        sudo cat >./30.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=R2iMq5LKXco)
        EOL
    - name: Get 31.m3u8
      run: |
        touch ./31.m3u8
        sudo cat >./31.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=-s6BflnoCrQ)
        EOL
    - name: Get 32.m3u8
      run: |
        touch ./32.m3u8
        sudo cat >./32.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get 33.m3u8
      run: |
        touch ./33.m3u8
        sudo cat >./33.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=MIqUplvSRWA)
        EOL
    - name: Get 34.m3u8
      run: |
        touch ./34.m3u8
        sudo cat >./34.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL
    - name: Get 35.m3u8
      run: |
        touch ./35.m3u8
        sudo cat >./35.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=68wEJkiC0y8)
        EOL
    - name: Get 36.m3u8
      run: |
        touch ./36.m3u8
        sudo cat >./36.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=jRsyBLhot6E)
        EOL
    - name: Get 37.m3u8
      run: |
        touch ./37.m3u8
        sudo cat >./37.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=RAP4h3q6_Sg)
        EOL
    - name: Get 38.m3u8
      run: |
        touch ./38.m3u8
        sudo cat >./38.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=F4aby5WN1Rw)
        EOL
    - name: Get 39.m3u8
      run: |
        touch ./39.m3u8
        sudo cat >./39.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=Ptg8ErmPjxM)
        EOL
    - name: Get 40.m3u8
      run: |
        touch ./40.m3u8
        sudo cat >./40.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=wrYF0HX7Kzc)
        EOL
    - name: Get 41.m3u8
      run: |
        touch ./41.m3u8
        sudo cat >./41.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1240000
        $(youtube-dl -g https://www.youtube.com/watch?v=GOiCIPAtdHA)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
