name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install youtube-dl
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
    - name: Get zsxw.m3u8
      run: |
        touch ./zsxw.m3u8
        sudo cat >./zsxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL    
    - name: Get cna.m3u8
      run: |
        touch ./can.m3u8
        sudo cat >./can.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=XWq5kBlakcQ)
    - name: Get tr.m3u8
      run: |
        touch ./tr.m3u8
        sudo cat >./tr.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=WIhgU_mc05A)
        EOL    
    - name: Get abc.m3u8
      run: |
        touch ./abc.m3u8
        sudo cat >./abc.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=w_Ma8oQLmSM)
    - name: Get slxww.m3u8
      run: |
        touch ./slxww.m3u8
        sudo cat >./slxww.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=uNEZ3hjamus)
    - name: Get msxw.m3u8
      run: |
        touch ./msxw.m3u8
        sudo cat >./msxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=P8DRJChuQQQ)
        EOL    
    - name: Get hyxw.m3u8
      run: |
        touch ./hyxw.m3u8
        sudo cat >./hyxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=EmhrRBJ1u9Q)
        EOL
    - name: Get ebcyouyou.m3u8
      run: |
        touch ./ebcyouyou.m3u8
        sudo cat >./ebcyouyou.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/yoyotvebc/live)
        EOL
    - name: Get ztxw.m3u8
      run: |
        touch ./ztxw.m3u8
        sudo cat >./ztxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=_QbRXRnHMVY)
        EOL
    - name: Get ebccj.m3u8
      run: |
        touch ./ebccj.m3u8
        sudo cat >./ebccj.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=ABn_ccXn_jc)
        EOL
    - name: Get tsxw.m3u8
      run: |
        touch ./tsxw.m3u8
        sudo cat >./tsxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL   
    - name: Get jxw.m3u8
      run: |
        touch ./jxw.m3u8
        sudo cat >./jxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=5n0y6b0Q25o)
        EOL
    - name: Get setxw.m3u8
      run: |
        touch ./setxw.m3u8
        sudo cat >./setxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=FoBfXvlOR6I)
        EOL
    - name: Get setcj.m3u8
      run: |
        touch ./setcj.m3u8
        sudo cat >./setcj.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=CKjSm5ZeehE)
        EOL
    - name: Get ebcxw.m3u8
      run: |
        touch ./ebcxw.m3u8
        sudo cat >./ebcxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=R2iMq5LKXco)
        EOL  
    - name: Get tvbs.m3u8
      run: |
        touch ./tvbs.m3u8
        sudo cat >./tvbs.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=YvdcZ_jpLXE)
        EOL
    - name: Get tvbsxw.m3u8
      run: |
        touch ./tvbsxw.m3u8
        sudo cat >./tvbsxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get thek.m3u8
      run: |
        touch ./thek.m3u8
        sudo cat >./thek.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=F4aby5WN1Rw)
        EOL
    - name: Get qqyy.m3u8
      run: |
        touch ./qqyy.m3u8
        sudo cat >./qqyy.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=wrYF0HX7Kzc)
        EOL
    - name: Get 8fm.m3u8
      run: |
        touch ./8fm.m3u8
        sudo cat >./8fm.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=GOiCIPAtdHA)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
